name: "Github Auto Commit"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        empty: true
        message: "Auto Commit "
        author_email: "l.l.wang@foxmail.com"
        author_name: "lleiwang"
        branch: "auto/commit"
